# Generated by Django 3.2.2 on 2021-05-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.ligue')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FTM', models.IntegerField(default=0)),
                ('FTA', models.IntegerField(default=0)),
                ('FGM', models.IntegerField(default=0)),
                ('FGA', models.IntegerField(default=0)),
                ('FGM_three', models.IntegerField(default=0)),
                ('FGA_three', models.IntegerField(default=0)),
                ('AST', models.IntegerField(default=0)),
                ('STL', models.IntegerField(default=0)),
                ('TO', models.IntegerField(default=0)),
                ('BLK', models.IntegerField(default=0)),
                ('OREB', models.IntegerField(default=0)),
                ('DREB', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('MIN', models.IntegerField(default=0)),
                ('PKT', models.IntegerField(default=0)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_opponent', to='liga.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stat', to='liga.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.ligue')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FTM', models.IntegerField(default=0)),
                ('FTA', models.IntegerField(default=0)),
                ('FGM', models.IntegerField(default=0)),
                ('FGA', models.IntegerField(default=0)),
                ('FGM_three', models.IntegerField(default=0)),
                ('FGA_three', models.IntegerField(default=0)),
                ('AST', models.IntegerField(default=0)),
                ('STL', models.IntegerField(default=0)),
                ('TO', models.IntegerField(default=0)),
                ('BLK', models.IntegerField(default=0)),
                ('OREB', models.IntegerField(default=0)),
                ('DREB', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('MIN', models.IntegerField(default=0)),
                ('PKT', models.IntegerField(default=0)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_opponent', to='liga.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=50)),
                ('referee', models.CharField(max_length=50)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='liga.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='liga.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.round')),
            ],
        ),
    ]
