# Generated by Django 3.2.2 on 2021-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_auto_20210511_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='on_court',
            field=models.BooleanField(default=False),
        ),
    ]
