# Generated by Django 3.2.2 on 2021-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_player_on_court'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'Player stats'},
        ),
        migrations.AlterModelOptions(
            name='teamstats',
            options={'verbose_name_plural': 'Team stats'},
        ),
        migrations.AddField(
            model_name='playerstats',
            name='Fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='Fouls',
            field=models.IntegerField(default=0),
        ),
    ]
