# Generated by Django 3.2.2 on 2021-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_auto_20210511_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
