# Generated by Django 3.2.2 on 2021-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0005_auto_20210517_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='TREB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='TREB',
            field=models.IntegerField(default=0),
        ),
    ]
