# Generated by Django 3.2.2 on 2021-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0006_auto_20210528_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='TREB',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='TREB',
        ),
        migrations.AddField(
            model_name='game',
            name='quarter',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.IntegerField(blank=True, default=600),
        ),
    ]
