# Generated by Django 3.2.2 on 2021-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0007_auto_20210531_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='TREB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='TREB',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
