# Generated by Django 3.2.2 on 2021-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0008_auto_20210531_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_ot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ot',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ot_time',
            field=models.IntegerField(blank=True, default=300),
        ),
    ]
