# Generated by Django 3.2.2 on 2021-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0009_auto_20210531_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
