# Generated by Django 3.2.2 on 2021-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0011_auto_20210618_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='nn.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, default='nn.jpg', upload_to=''),
        ),
    ]
