# Generated by Django 3.2.2 on 2021-06-25 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0013_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hour',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
