# Generated by Django 3.2.2 on 2021-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0015_game_reset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reset_ot',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
