# Generated by Django 3.2.2 on 2021-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0017_alter_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.CharField(choices=[('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i'), ('i', 'i')], default='1', max_length=5),
        ),
    ]
