# Generated by Django 3.2.2 on 2021-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0022_alter_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
